In [4]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [6]:
# load and read data
data = pd.read_csv('gdrive/MyDrive/Aplikasi Pembelajaran Mesin/Pertemuan 6/Dataset/minimarket.csv',
                   delimiter=';', header=None)
data.head()

       0         1          2         3        4        5    6
0   Milk     Onion        Jam  Biscuits     Eggs  Yoghurt  NaN
1  Onion       Jam   Biscuits      Eggs  Yoghurt      NaN  NaN
2   Milk  Biscuits      Apple      Eggs      NaN      NaN  NaN
3   Milk     Bread  Ice Cream  Biscuits      NaN      NaN  NaN
4  Onion      Eggs        NaN       NaN      NaN      NaN  NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       156 non-null    object
 1   1       150 non-null    object
 2   2       116 non-null    object
 3   3       74 non-null     object
 4   4       39 non-null     object
 5   5       18 non-null     object
 6   6       2 non-null      object
dtypes: object(7)
memory usage: 8.7+ KB

In [8]:
data = data.values.astype(str)

In [9]:
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)

In [10]:
df = pd.DataFrame(te_ary, columns=te.columns_)
df.head()

,Apple,Avocado,Biscuits,Bread,Butter,Eggs,Ice Cream,Jam,Milk,Onion,Yoghurt,nan
0,False,False,True,False,False,True,False,True,True,True,True,True
1,False,False,True,False,False,True,False,True,False,True,True,True
2,True,False,True,False,False,True,False,False,True,False,False,True
3,False,False,True,True,False,False,True,False,True,False,False,True
4,False,False,False,False,False,True,False,False,False,True,False,True

In [11]:
df = df.drop('nan', axis=1)
df.head()

,Apple,Avocado,Biscuits,Bread,Butter,Eggs,Ice Cream,Jam,Milk,Onion,Yoghurt
0,False,False,True,False,False,True,False,True,True,True,True
1,False,False,True,False,False,True,False,True,False,True,True
2,True,False,True,False,False,True,False,False,True,False,False
3,False,False,True,True,False,False,True,False,True,False,False
4,False,False,False,False,False,True,False,False,False,True,False

In [12]:
freq_itemsets = apriori(df, min_support=0.3, use_colnames=True)
freq_itemsets

    support       itemsets
0  0.301282     (Biscuits)
1  0.467949        (Bread)
2  0.557692         (Eggs)
3  0.391026         (Milk)
4  0.435897        (Onion)
5  0.378205  (Eggs, Onion)

In [13]:
res = association_rules(freq_itemsets, metric='confidence', min_threshold=0.3)
res

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Eggs),(Onion),0.557692,0.435897,0.378205,0.678161,1.555781,0.135108,1.752747
1,(Onion),(Eggs),0.435897,0.557692,0.378205,0.867647,1.555781,0.135108,3.341880

In [14]:
res1 = res[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
res1

  antecedents consequents   support  confidence      lift
0      (Eggs)     (Onion)  0.378205    0.678161  1.555781
1     (Onion)      (Eggs)  0.378205    0.867647  1.555781